# Generated by Django 3.2.9 on 2021-11-28 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='function',
            new_name='foundation',
        ),
    ]
